### ISSUE TITLE
App crashes (5s 10.x)

### ISSUE THREAD

**Issue by piji6** [djphoenix/MoneroKit#1]
Heya,

Just downloaded your app (iphone 5S iOS 10), it crashes after about 10 seconds.
Feel free to contact me for bugfinding.

**Comment by djphoenix** [comment]
Hi @piji6!
Are you use version 1.0.1? It have some improvements for stability.
I receiving crash reports from iTunes Connect, so will fix all of them in further releases.

**Comment by 76344243** [comment]
Hi! I am very excited about your app but it is impossible to use it in background (standby) since the app is terminated after a few minutes. At least there is a message.... 

I´m using an iPad Pro 9.7 + 12.9 (2017). 

Hoepfully you will solve that issue, otherwise your great app is unusable... Good luck!

PS: Most actual iOS 11

**Comment by djphoenix** [comment]
@76344243 yes, background mode uses hacks "on the edge" of Apple Policies, so this is very limited. I'm working on background keeping for longer time. Stay tuned!

**Comment by 76344243** [comment]
Thank you for your kind response. Hopefully this will manage to work.
I just switched from xmrpool to minexmr.com and now the app really crashes very quickly while it just was terminated with other pools. I tried different pool addresses and ports but it doesn´t help... Maybe you app has issues with special pool settings?

**Comment by djphoenix** [comment]
@76344243 I'll test minexmr.com. Can you provide example configuration that causes crash? You may mask your address if you want.

*UPD:* Oh, I found an issue... yes, minexmr.com will fail for current version. I preparing a new release, it will be in store in next days.

**Comment by 76344243** [comment]
OK, too late it seams .... GREAT WORK!!!! 

PS: I´m getting about 40 H/s on my iPad Pro 2017 and ask myself what Metal will be able to push it further.... Also I wonder what the result might be on the new A11 SoC.....

**Comment by djphoenix** [comment]
@76344243 I started first experimental version of Metal kernel on my iPhone SE (A9 GPU), and it takes improvement about 15H/s (128 hash-chunk in ~8.5s). It will be available in next update. Unfortunately, Metal works only in foreground.

**Comment by 76344243** [comment]
15kh/s ??? WOW!!! Amazing!! If the A10x does 40 and there was a massive gpu performance gain it might reach even twice as much or more. My 7700K CPU just makes 120.... for much more energy... btw do you also use the multiple cores on the iPad SoCs?

**Comment by djphoenix** [comment]
15H, not kH... :) Cryptonight is very slow just because number of operations.
I use automatic CPU core number detection, of course. And run parallel thread for each one.

In next weeks I will prepare project to be open-source, so you can just see how it works :)

**Comment by 76344243** [comment]
Ahhh, of course H/s .. of course... I just made a mistake... 😂

**Comment by djphoenix** [comment]
@piji6 @76344243 if you want to access new app builds in a first row, write me (github@phoenix.dj), and I will send you invites to TestFlight group.

**Comment by SimaFish** [comment]
Hi! The app is definitely the one I've looking for. But, unfortunatelly, it crashes after a few seconds of work... iPad Air 2, iOS 11.2.1 - will it be an updated version soon? How can I fix this? Thank you!
