### ISSUE TITLE
Crash during debugger

### ISSUE THREAD

**Issue by cmorsucci** [djphoenix/MoneroKit#10]
After launching the debugger via XCode on my iPhone device, I get this error .. if I run the application without debugger it works correctly..

`-[MTLDebugDevice validateNewBufferArgs:options:]:366: failed assertion newBufferWith*:length 0x20000000 must not exceed 256 MB.'`

**Comment by djphoenix** [comment]
Try to disable Metal API Validation in scheme settings. It definitely works :)
![2018-05-13 22 54 00](https://user-images.githubusercontent.com/1833493/39971258-a56f327c-5700-11e8-8731-bc542c5bdde2.png)

**Comment by cmorsucci** [comment]
Ok, thanks, it works
