### ISSUE TITLE
Implicit conversion changes signedness

### ISSUE THREAD

**Issue by noatte** [djphoenix/MoneroKit#16]
I have the following error when I try to build the MoneroKitSample :

`Implicit conversion changes signedness: 'HashReturn' to 'int'`

in this file :
![Capture d’écran 2021-03-02 à 20 07 04](https://user-images.githubusercontent.com/49617162/109701035-ddb4fe00-7b92-11eb-882b-1228899f3983.png)

Can someone helps me fix the issue ?

Thanks :)

**Comment by iPurpl3x** [comment]
Just replace `int` with `HashReturn`. Worked for me.

**Comment by noatte** [comment]
> Just replace `int` with `HashReturn`. Worked for me.

Thanks ! It worked
