### ISSUE TITLE
Nicehash

### ISSUE THREAD

**Issue by Alexakazam** [djphoenix/MoneroKit#4]
I can't get this app to work with the nicehash stratum pools. Am I doing something wrong? Don't see why I can't just add this as another nicehash worker using the same btc address, but I have no idea. I tried inputting an xmr address and that didn't work either. Is the nicehash stratum just not supported?

**Comment by djphoenix** [comment]
I haven't tested a "nicehash" algorithm, maybe it's really not supported (yet). But I will add official support for nicehash in nextup updates.

BTC addresses are not supported anyway, miner allowed to use for only Monero XMR (or another Cryptonight-based currencies, but not officially supported).

**Comment by Alexakazam** [comment]
Cool, thanks for the reply. I did get this to work with an xmr address and xmrsupport.com pools. App seems to work fine, but some nicehash pools would be a cool addition.

**Comment by djphoenix** [comment]
@Alexakazam FYI: I have tested mining for NiceHash.com (amazing, it uses BTC address as login for cryptonight pool). With some minor modifications, I have made it work. Unfortunately these changes will not be in next release of app in AppStore because I'm already waiting for approve next version. But in next (1.0.3) version Nicehash will be supported.

**Comment by Alexakazam** [comment]
You didn't know about nicehash and that it does that? Seems like you thought I was on drugs or something, "you can't add no bitcoin address to this miner, its for xmr and xmr wallet addresses"... well yeah... but nicehash uses btc addresses as the cryptonight pool.. seems like you don't know much about mining.

**Comment by djphoenix** [comment]
@Alexakazam oh, well...
> You didn't know about nicehash and that it does that?

I know about nicehash *algorithm*, but was never used nicehash *service* before.
> Seems like you thought I was on drugs or something

I'm very sorry, but I have replied for so much App Store Reviews with so much dumb questions... So I was confused about BTC address. Sorry again :)
> seems like you don't know much about mining.

I know many things about many regions of IT... But not everything, of course.
