### ISSUE TITLE
Xcode Error

### ISSUE THREAD

**Issue by mikemike396** [djphoenix/MoneroKit#5]
I am getting these errors when I try and run the sample code on a simulator. I am running Xcode 9.2

![screen shot 2018-01-10 at 8 23 16 am](https://user-images.githubusercontent.com/14999806/34775273-93092c54-f5e0-11e7-8354-235ffced1aed.png)

**Comment by djphoenix** [comment]
Metal is not supported in Simulator. You may try to temporary disable MoneroMetal dependency in MoneroKit...

**Comment by djphoenix** [comment]
@mikemike396 please check latest master - I have disabled Metal build for `iphonesimulator` so now it will work.
