### ISSUE TITLE
App not in iOS Store any more.

### ISSUE THREAD

**Issue by rendia** [djphoenix/MoneroKit#6]
Hello Yury Popov,
your is not in store any more. What‘s happened?

I like your app to mine monero. It‘s cute, efficient and powerful - great. I use it on iPad Pro.

Do you plan to bring it back?

Greetings from Potsdam, Germany.
René

**Comment by djphoenix** [comment]
@rendia unfortunately Apple was removed an app from store, I'm discuss with support about this decision, but they're answers slowly...

As an workaround for now, you may [write me an email](mailto:github@phoenix.dj), so I can invite you to TestFlight group with access to latest version.

**Comment by mikemike396** [comment]
Wow I am curious on their reason. This is interesting.

**Comment by mikemike396** [comment]
Any update on this?

**Comment by djphoenix** [comment]
Unfortunately no progress now for this problem. But I will try again and again to get it back :)
