### ISSUE TITLE
POW v7 not implemented

### ISSUE THREAD

**Issue by nclr** [djphoenix/MoneroKit#7]
Are you planning on updating to the pow7?

**Comment by djphoenix** [comment]
@nclr I definitely will update to POW7, I have a look on new mechanics and changes looks simple.

**Comment by slax0r** [comment]
Any updates on this?

**Comment by Tzadok85** [comment]
Checking in - also very curious about an update...Have not yet had the opportunity to use this...but am definitely interested in checking it out. 👍

Any info or potential/desired timeline for an update? 

Thanks!

**Comment by djphoenix** [comment]
Sorry for delay, I was very busy on primary work projects, but now it's done.

**Comment by slax0r** [comment]
Thank you so much for this great project and your hard work!
